<font size="6"> **Python Basics**</font>

<font size="5"> 1. Split this string</font>

In [ ]:
s = "Hi there Sam!"

In [ ]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


<font size="5"> 2. Use .format() to print the following string.</font>

<font size="4"> Output should be: The diameter of Earth is 12742 kilometers.</font>

In [ ]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


<font size="5"> 3. In this nest dictionary grab the word "hello"</font>

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


<font size="6"> **Numpy**</font>

In [ ]:
import numpy as np

<font size="5"> 4.1 Create an array of 10 zeros?</font>

<font size="5"> 4.2 Create an array of 10 fives?</font>

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


<font size="5"> 5. Create an array of all the even integers from 20 to 35</font>

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


<font size="5"> 6. Create a 3x3 matrix with values ranging from 0 to 8</font>

In [ ]:
array1=np.arange(0,9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<font size="5"> 7. Concatenate a and b</font>

<font size="5"> a = np.array([1, 2, 3]), b = np.array([4, 5, 6])</font>

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


<font size="6"> **Pandas**</font>

<font size="5"> 8. Create a dataframe with 3 rows and 2 columns</font>

In [ ]:
import pandas as pd
data=[["Vishal",1],["Gaju",2],["Hari",3],["Josh",4],["Diran",5]]
data1=pd.DataFrame(data,columns=["name","age"])
print(data1)

     name  age
0  Vishal    1
1    Gaju    2
2    Hari    3
3    Josh    4
4   Diran    5


<font size="5"> 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023</font>

In [ ]:
data4=pd.date_range(start="1-01-2023",end="10-02-2023",freq="5h")
print(data4)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 05:00:00',
               '2023-01-01 10:00:00', '2023-01-01 15:00:00',
               '2023-01-01 20:00:00', '2023-01-02 01:00:00',
               '2023-01-02 06:00:00', '2023-01-02 11:00:00',
               '2023-01-02 16:00:00', '2023-01-02 21:00:00',
               ...
               '2023-09-30 02:00:00', '2023-09-30 07:00:00',
               '2023-09-30 12:00:00', '2023-09-30 17:00:00',
               '2023-09-30 22:00:00', '2023-10-01 03:00:00',
               '2023-10-01 08:00:00', '2023-10-01 13:00:00',
               '2023-10-01 18:00:00', '2023-10-01 23:00:00'],
              dtype='datetime64[ns]', length=1316, freq='5H')


<font size="5"> 10. Create 2D list to DataFrame</font>

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
data2=pd.DataFrame(lists,columns=["s.no","Name","marks"])
print(data2)

   s.no Name  marks
0     1  aaa     22
1     2  bbb     25
2     3  ccc     24
